### ISSUE TITLE
ロゴ作成

### ISSUE THREAD

**Issue by makomsh** [croud-c3/croud-c3.github.io#12]
どんな感じにするか悩み中
C3でいくか
CCCでいくか…
CCCにしてフォントでよい感じにロゴ感を出すのが最有力候補かな。

**Comment by makomsh** [comment]
迷走中
![logo](https://cloud.githubusercontent.com/assets/19387384/20090774/8c294e64-a5d2-11e6-84d8-94176f66f41b.jpg)

**Comment by k-on910** [comment]
![default](https://cloud.githubusercontent.com/assets/21698258/20122190/4cbccd6e-a659-11e6-98dc-7201fa3e7bbd.jpg)

**Comment by k-on910** [comment]
![1](https://cloud.githubusercontent.com/assets/21698258/20175027/37c2b956-a784-11e6-880e-afc1cfe4d406.jpg)
