### ISSUE TITLE
企業側マイページに載せる学生の名刺をつくる（またはフリー素材を探す）

### ISSUE THREAD

**Issue by menphim** [croud-c3/croud-c3.github.io#6]

**Comment by makomsh** [comment]
とりあえずこんな感じで
![meishi12](https://cloud.githubusercontent.com/assets/19387384/19921488/70afd104-a121-11e6-8ddd-b4840ceba9a1.jpg)
![meishi13](https://cloud.githubusercontent.com/assets/19387384/19921491/71ba07d6-a121-11e6-9f51-507cff9aa77d.jpg)
![meishi15](https://cloud.githubusercontent.com/assets/19387384/19921492/737e621a-a121-11e6-8f4c-f0bfb1b407d1.jpg)
